version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    install:
      - pip install --verbose .[docs]
    build:
      html:
        - jupyter-book build --builder html --warningiserror --path-output $READTHEDOCS_OUTPUT/html/ docs/
  
